version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/home/administrator/test/blockscout/docker-compose/proxy"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://host.docker.internal:4001}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://host.docker.internal:3001}
    ports:
      - target: 81
        published: 81
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
